follower_costmap:
  map_type: costmap
  global_frame: map
  robot_base_frame: move_base

  footprint: [[-0.36, -0.250], [-0.36, 0.250], [0.36, 0.250], [0.36, -0.250]]

  update_frequency: 10.0
  publish_frequency: 5.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.05

  static_layer:
    enabled: true
    track_unknown_space: true
    map_topic: "/map"
  inflation_layer:
    enabled: true
    cost_scaling_factor: 8.0
    inflation_radius: 0.5

  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

robot_model:
  footprint: [0.72, 0.50]
