planner_costmap:
  map_type: costmap
  global_frame: map
  robot_base_frame: move_base

  footprint: [[-0.36, -0.250], [-0.36, 0.250], [0.36, 0.250], [0.36, -0.250]]

  update_frequency: 2.0
  publish_frequency: 1.0
  transform_tolerance: 0.5

  static_map: true
  rolling_window: false

  static_layer:
    enabled: true
    track_unknown_space: true
    map_topic: "/map"
  inflation_layer:
    enabled: true
    cost_scaling_factor: 8.0
    inflation_radius: 0.5

  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

collision:
  footprint: [0.64,0.46] # 一个数代表圆，两个数字代表长宽，四个数字代表四个边界点x1y1 x2y2
  hole: true # footprint是否只使用边界 

path_planner:
  max_sec: 0.5 # 规划超时时间
  minimum_turning_radius: 0.84 # 最小转弯半径
  cost_penalty: 2.0 # footprint 的惩罚系数
  change_penalty: 0.01 # 转向的的惩罚系数
  non_straight_penalty: 1.2 # 非直线的惩罚系数
  reverse_penalty: 3.0 # 倒车的惩罚系数
  analytic_expansion_ratio: 1.0 # 启发式搜索的比例(每1.0米进行一次启发式搜索)
  analytic_expansion_tolerance: 3.0 # 启发式搜索的阈值（距离目标点的距离3.0米开始启发式搜索）
  max_iterations: 100000 # 最大迭代次数
  max_on_approach_iterations: 1000 # 最大接近目标点后的迭代次数
  motion_type: ReedsShepp # 曲线模型
  tolerance: 0.6 # 在目标点0.6米以内时进行小范围搜索
  angle_quantization_bins: 72 # 角度量化角度

smoother:
  max_iterations: 1000 # 最大迭代次数
  w_data: 0.2 # 数据权重
  w_smooth: 0.3 # 平滑权重
